### ISSUE TITLE
not work with Settings Sync(shan.code-settings-sync)

### ISSUE THREAD

**Issue by HiramChen-CN** [myfreeer/vscode-portable#1]
after I put version.dll in the same folder of Code.exe, Settings Sync not work, any things can't be sync with github.

**Comment by myfreeer** [comment]
That's because the extension does not honor `VSCODE_APPDATA` environment variable, just [ask them](https://github.com/shanalikhan/code-settings-sync/issues/new/choose) to implement support. 

Check [src/paths.js of vscode](https://github.com/Microsoft/vscode/blob/caa5334413292ce22613bda9468d91d466c49ff5/src/paths.js#L20) and [src/environmentPath.ts of code-settings-sync](https://github.com/shanalikhan/code-settings-sync/blob/bd822f7a95ef6baeae0747b045b915c045d158fd/src/environmentPath.ts#L67) for more details.
